---
title: "Set Up Instructions"
author: "Math 115"
date: "11/15/2020"
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Math 115:  Set up your working environment 

## GitHub.    
Establish a GitHub account, it is free.  This is necessary because you will get write-up problems through GitHub.   You will also submit write-ups for grading by completing your assignment and pushing it to your GitHub account and the submitting the write-up URL.
a.	Got to https://github.com/  Select the ‘Sign Up’ button 

  
Select a username, I recommend you use your AVC email account and select your password.  BE SURE TO REMEMBER YOUR USERNAME AND PASSWORD. We suggest your AVC email as the username, and your AVC email password as the password. If you use something other than the AVC credentials, WRITE THEM DOWN.  These are username and password for you GitHub account.  If you forget either, you will not be able to access your GitHub account.

## Rstudio.cloud.   
Rstudio.cloud is the free software we use for statistical analysis and reporting.  Establish two Rstudio.cloud accounts, one using your AVC.EDU email address and one using another email address:  https://rstudio.cloud/  

Select the Free student account for both.  You need two Rstudio.cloud accounts because the free accounts limit you to 15 hours and 15 projects each.  We will link the two accounts

  1. Set up a shared account and a base project in each 
  2. In each individual account add these packages and their dependencies to your base project.  Here is the list tidyverse, tigerstats,knitr,car,leaps,leaps.  
  
### How to make a shared space  

A shared space is an area where a group of people can collaborate together - only the members of a shared space can access the space and its contents.  A shared space is important in that you can incorporate a 'base' project-- i.e. one that has preloaded packages

To create a shared space on the navigation menu (the menu icon at the upper left) and choose New Space, then follow the on-screen instructions.


**Members**  
After creating a space, go to the Members area to manage its membership. You can add members to your space in two ways:

   1. To add members one by one, choose the Invitation Required option, and send invitations to each person you’d like to add to the space via the Add Member button.
  
  2. To allow many people to join the space, choose the Sharing Link option, copy the sharing link and then share that link with all whom you’d like to join the space, either via an email or by posting the link on a web page. Keep in mind that anyone with that link can join your space. If you would like to disable a link you previously shared, choose **Reset Sharing Link;** this will prevent any additional people from joining the space using that link.

Note that you can switch the access option at any time - a common approach is to initially set the access option to Sharing Link, post the sharing link, then after all the people you want to join the space have done so, switch access to Invitation Only. The original sharing link will no longer allow additional people to join the space, but you can add any new members individually.
  
**Roles**  

Each member of a space is assigned as a contributor when he/she joins the space.

### How to create a base project  

To install a base project you must be in a "shared space" first.  
Now go to your shared space and start a new project and name the project "mybase".
Change the "visibility" of the project so that everyone can see it.

Now go back to viewing all the projects in your shared space and click on
settings and make "mybase" the base project. 

Next, from the window where you made mybase the base project you edit it.

First add version control to it by going to tools -> version control -> git
Then choose tools -> Install Packages -> and choose tidyverse, tigerstats, knitr

Later we will come back and install more packages as we move through the course.

### How to link shared spaces, and invite others to your space

You can invite other people to collaborate with you in a shared space that you control
(i.e. that you are listed as the admin of that space).  For several reasons it is wise 
to only make invitees to your space "contributors".  This is especially true if the other 
person is you with a different email identity.  So invite your other identity to share your space.
It will send you an email that you need to acknowledge in order to be a member of that space. Another 
important thing to keep in mind is the name you give to your shared space. My suggestion is to have the 
name of your shared space clearly indicate which email identity it is associated with. You will need to 
repeat this process for every shared space you acquire. The whole reason you are doing this is to gain more resource elbow room.  With this approach when you are running out of time in one shared space you simply move the project to another space where you have more time available.  Don't get in the habit of leaving projects pile up in rstudio.cloud shared spaces. The mindset to adopt is that github is your project locker room. Rstudio.cloud is a workshop that you try to keep as clean as possible. When its time to continue work on a project you start anew from the github repository where you keep it. When you finish your work, commit your changes and push them back up to github, then delete your project from your rstudio.cloud shared space.
